import { Roboto } from "next/font/google";
import "./globals.css";
import BootstrapClient from "./components/BootstrapClient";

const roboto = Roboto({
  subsets: ["latin"],
  weight: [ '500', '700' ],
});

export const metadata = {
  title: "Zoiko Mobile USA",
  description: "Generated by Zoiko Mobile",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
